### PR TITLE
corrected Windows SDK requirement

### PR DESCRIPTION
**Pull request by Z-Shang**

### CODE REVIEW

**Comment by yatli** [comment]
testing

**Comment by Z-Shang** [comment]
meow

2018年5月11日(金) 14:53 Yatao Li <notifications@github.com>:

**Comment by yatli** [comment]
confirmed: Trinity.C build fails without SDK 15063

**Comment by yatli** [comment]
fixed by downgrading to sdk 10586. all .vcxproj files updated. closing this PR now.

**Pull request closed without merging**
