### PR TITLE
Misc: update build script for nuget source adding

### PR DESCRIPTION
**Pull request by leasunhy**

### CODE REVIEW

**Comment by yatli** [comment]
ok please test this

**Comment by yatli** [comment]
[YataoBot] Can one of the admins verify this patch?

**Comment by yatli** [comment]
ok to test!

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Comment by leasunhy** [comment]
retest this please

**Pull request merged**
