### PR TITLE
README update

### PR DESCRIPTION
**Pull request by Mandelliant**
Cleans up links, reorganizes content for better reading flow, minor copy edits and revisions

### CODE REVIEW

**Comment by Mandelliant** [comment]
Happy to make any necessary changes to pass the CI checks. Additionally, if I've done anything wrong in preparing my PR, I can add any missing steps to the How to Contribute section

**Comment by yatli** [comment]
hi @Mandelliant thanks for your contribution! The PR build fails because of incorrect configuration. I'm kicking start a new build.

**Comment by yatli** [comment]
hmm, I guess it'll be retriggered once you leave a comment (as observed in another PR)

**Comment by Mandelliant** [comment]
@yatli hmm interesting - hoping this retriggers it!

**Comment by Mandelliant** [comment]
@yatli Doesn't seem like that worked - if you need me to change anything in the PR, just let me know

**Comment by yatli** [comment]
@Mandelliant I made a trivial change and then it kicked started

**Review by yatli — APPROVED** [review]
LGTM

**Comment by yatli** [comment]
thanks for your contribution!

**Pull request merged**
