### PR TITLE
Add Support to run GE in Azure Service Fabric

### PR DESCRIPTION
**Pull request by TaviTruman**
With the advent of the Microsoft Graph Engine and its amazing RDF-centric Graph-compute capabilities combined with flexibility, power and reliability of the Azure Service Fabric, developers can design and develop a new breed and class of systems, application and business Microservices enabling domains and markets of all shape, size and complexity, ushering in the power of the GE Type-Safe Memory Cloud and Graph-based compute power.

At present that GE App workflow does not support simple and seamless integration of Service Fabric Stateless or Stateful Reliable Service App Models. In addition, one of the value-adds of the developing GE and Service Fabric enable services and client software is the ability to use local machine resources before publishing software up to Azure; thus, it is imperative that we create software libraries in support of GE-enabled SF Microservices as well as provide Visual Studio Integration for Local and Remote development and deployment of GE and Service Fabric software.

The goal of this pull-request is to provide the following:
o C# and F# enablement and support of seamless integration of the machine generate GE Server into the Service Fabric Architecture, Application model, Communication Subsystem, Reliability Subsystem, Hosting and Testing Subsystems.
o	IEnumerable<ServiceInstanceListerner> CreateServiceInstanceListeners()
o	IEnumerable<ServiceReplicaListerner> CreateServiceReplicaListeners()
o	Stateless configuration
o	Stateful configuration
o	Custom Communication Stack for GE
	Protocol Support
•	HTTP
•	TCP
	ICommunicationListerner implementation in support of GE
o	Stateful computing
	Reliable Service Implementation for GE
	Support for Reliable Collection and the GE Memory Cloud
	Transaction Replication
•	Provide GE Templates in support of Service Fabric Application
•	Provide Simple and Moderate completeness and complexity sample GE-enabled SF-Ready Applications

### CODE REVIEW

**Comment by yatli** [comment]
Hi Tavi!

Let's do this. Leo and I will join the effort.

**Comment by TaviTruman** [comment]
Excellent and looking forward to working with you and Leo.

**Comment by TaviTruman** [comment]
@yatli what branch do  you want to me to work against?

**Comment by yatli** [comment]
@TaviTruman I'm considering to create a new branch `availability`, where we can work on the service fabric, and also make abstractions to support other infrastructures such as zookeeper.

**Comment by TaviTruman** [comment]
@yatli Understood. As you are aware that I am working on technology wholly based on the GE and want to make parts of it available via GitHub Open Source, e.g. RDF, RDFS and OWL 2 API, etc. I'm fine with them organized under GE as opposed to creating new repositories. What do you think?

**Comment by yatli** [comment]
@TaviTruman We're happy with this plan. Necessary abstractions and core support go into GE core, and RDF related technology can reside in parallel with LIKQ, SPARQL and SPARK-connector, as our plug-and-play modules for the users, all in the same repo. :)

**Comment by TaviTruman** [comment]
@yatli I want to start moving code up to GutHub; we have been working in TFS for years now and one of my development leads is working get parallel builds up and running for TFS and GitHub. For the GE Service Fabric are we going to us "Availability" root?

**Comment by yatli** [comment]
@TaviTruman If we are specifically working on Service Fabric, I suggest that we place it under `src/Modules`.

I'll start the branch as soon as we get the test suite properly moved to Azure. Hang on :)

**Comment by TaviTruman** [comment]
Okay that makes sense; also, I'm writing the Visual Studio add in to support GE/SF workflow - might we add a place to store said productions?

**Comment by yatli** [comment]
@TaviTruman cool, how about `src/Utilities`? We can also put other stuff like TSL syntax highlighter for various editors, VS Code integration there.

**Comment by yatli** [comment]
[YataoBot] Can one of the admins verify this patch?

**Comment by yatli** [comment]
@TaviTruman We have finished wrapping up our work and merged it back to `master`. I've created the `availability` branch (which is now on par with `master`) and please fork it and send PRs to us.

Also, please feel free to open issues to discuss anything with us, we are more than happy that we can explore the new possibilities together.

**Comment by TaviTruman** [comment]
@yatli That's great news. I'll start pushing PRs and Discussions and I'm looking forward to working together you and members of the GE team!

**Comment by grahamehorner** [comment]
It's great that the team is working on this, been interested in graph.io since the project was called trinity 😎 wondering if this will include within the scope a version of graph.io that will run under .net core on Linux ? I'd be happy to help out with any up for grabs items

**Comment by yatli** [comment]
@grahamehorner The preliminary Linux support has recently made it into `master`, please check it out. :)
It would be great if you can set up a linux box and play with it, and let us know if you have any problems!

**Comment by TaviTruman** [comment]
@yatli I've got new machines setup for GE and Service Fabric and moving my current GE/SF development on to a bigger server cluster for GE/SF execution and testing. I'm preparing a few docs that describe the development environment and how to setup and test first.

**Comment by yatli** [comment]
@TaviTruman Good to know! Looking forward to it!
I've drafted some bits about hosted environment integration, here: https://github.com/Microsoft/GraphEngine/issues/108, please take a look :)

**Comment by TaviTruman** [comment]
@yatli Great write-up! I'm reading over it now and adding my thoughts relative to Service Fabric.

**Comment by TaviTruman** [comment]
@yatli I need some help and guidance in how best to use the Trinity Networking stack; I'm going to push my existing samples and working code up the GitHub later on today (July 12, 2017).

**Comment by TaviTruman** [comment]
@yatli Hello - I am getting Authentication failure errors when trying to publish.

**Comment by yatli** [comment]
@TaviTruman really excited about this!
I guess you are trying to push to this repo? Unfortunately this repo is owned by the MS organization and you will have to fork a branch and create PR.

**Comment by TaviTruman** [comment]
Okay so I need to do a pull request against "availability" right?

**Comment by yatli** [comment]
Yes, totally.

**Comment by TaviTruman** [comment]
Okay got it!

**Comment by TaviTruman** [comment]
Yikes I'm still getting "Request Failed with Status Code: 403" - that is  HTTP 403 Forbidden status in response to a request from a client. I'll continue to work on this in the AM.

**Comment by yatli** [comment]
Closed mistakenly. @TaviTruman could you please change your target branch to `availability`? I realized that I cannot reopen it myself because the target branch `dev` of this PR is already gone. Thanks!

**Comment by TaviTruman** [comment]
@yatli yes I will get that done later on today.

**Comment by yatli** [comment]
[YataoBot] Can one of the admins verify this patch?

**Comment by TaviTruman** [comment]
Hey @yatli - I made the change to the "Target" branch, altering it from master to "availability."

**Comment by yatli** [comment]
ok to test, YataoBot!

**Comment by yatli** [comment]
@TaviTruman done merging, but I think this PR is pointing from MS:master to MS:availability rather than your repo (so that when I try to update MS:availability, this PR is automatically merged)

**Pull request merged**
